### ISSUE TITLE
Does not work in Dragonflight Pre-Patch

### ISSUE THREAD

**Issue by ghost** [Debuggernaut/LucidNightmareHelper#10]
Hello, 

Just tried to use the addon to finish the final step but was met with the lua error below:

`Message: ...s/LucidNightmareNavigator/libs/NyxGUI-1.0/NyxGUI.lua:238: Usage: self:SetFont(fontFile, height, flags)
Time: Thu Oct 27 16:50:55 2022
Count: 1
Stack: ...s/LucidNightmareNavigator/libs/NyxGUI-1.0/NyxGUI.lua:238: Usage: self:SetFont(fontFile, height, flags)
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/LucidNightmareNavigator/libs/NyxGUI-1.0/NyxGUI.lua"]:238: in function <...s/LucidNightmareNavigator/libs/NyxGUI-1.0/NyxGUI.lua:231>
[string "@Interface/AddOns/LucidNightmareNavigator/libs/NyxGUI-1.0/NyxGUI.lua"]:255: in function `UpdateTheme'
[string "@Interface/AddOns/LucidNightmareNavigator/libs/NyxGUI-1.0/NyxGUI.lua"]:286: in function `SetThemeData'
[string "@Interface/AddOns/LucidNightmareNavigator/libs/NyxGUI-1.0/NyxGUI.lua"]:297: in function `LoadTheme'
[string "@Interface/AddOns/LucidNightmareNavigator/libs/NyxGUI-1.0/NyxGUI.lua"]:140: in function `Initialize'
[string "@Interface/AddOns/LucidNightmareNavigator/libs/NyxGUI-1.0/NyxGUI.lua"]:390: in main chunk

Locals: (*temporary) = NyxGUIdefaultFontlabel {
 0 = <userdata>
}
(*temporary) = "Fonts\FRIZQT__.ttf"
(*temporary) = 10
(*temporary) = nil`

Just thought you would like to know.

Thanks for the addon btw

**Comment by Debuggernaut** [comment]
Oh, sorry about that, I'll go fix the addon after work

The ui library I'm using probably just needs an update for 10.0..

**Comment by Debuggernaut** [comment]
DONE!!  (half-assedly)
