### ISSUE TITLE
Does not work in Shadowlands Pre-patch 

### ISSUE THREAD

**Issue by DigitallyCreativeDesigns** [Debuggernaut/LucidNightmareHelper#3]
If you type /ln or /lucid nothing happens. You can't even click enter.

**Comment by Debuggernaut** [comment]
Ah shoot, sorry man, I'll take a look at it when I get a chance

I'm super slammed with work right now though, so it might take a while.  Hopefully this is just a minor issue I can work around quickly, and not some fundamental change in the game API.. the mapping and pathfinding code is all portable, but without the automatic detection of which direction you went, the addon will be pretty worthless

**Comment by DigitallyCreativeDesigns** [comment]
Yeah I understand. Sucks for me haha I had the maze all figured out before servers went down and now the addon doesn't work. Obviously not your fault but now I'm kicking myself for being so close and missing it by a few minutes.

**Comment by DigitallyCreativeDesigns** [comment]
Do you think it could be something with the slash command or does that not matter? Like can we just initialize it without that command?

**Comment by Debuggernaut** [comment]
Hmm, my guess is that either one of your addons is hiding lua errors, or lua errors are turned off.  Chances are pretty good, though, that if you unhide errors it'll be like that scene from Indiana Jones where he lights a torch and it turns out he's completely surrounded by deadly snakes.

I set a reminder for this weekend, I'm sure I can scrape together a couple of hours to tackle this.. so **don't feel obligated to delve into the horrible river of human waste that runs below WoW's UI**

You can turn on showing lua errors via:

/console scriptErrors 1

or if you have BugGrabber installed (it comes prepackaged with some addons and addon packs) you can install BugSack and use it to see the Lua bugs

If you end up looking at it yourself, you can see WoW API changes here:  https://github.com/Gethe/wow-ui-source/tree/ptr

Visual Studio code is a good way to visualize lua syntax, but I haven't found a good full IDE for WoW addons

**Comment by DigitallyCreativeDesigns** [comment]
Awesome thanks for the info! I do have some experience in lua but you are 100% right about the snakes. Below is the error I get just so you can take a look. Thanks for this btw the addon is super helpful!

`Message: ...s\LucidNightmareNavigator\libs\NyxGUI-1.0\NyxGUI.lua:199: attempt to call method 'GetBackdrop' (a nil value)
Time: Tue Oct 13 20:39:39 2020
Count: 2
Stack: ...s\LucidNightmareNavigator\libs\NyxGUI-1.0\NyxGUI.lua:199: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\LucidNightmareNavigator\libs\NyxGUI-1.0\NyxGUI.lua"]:199: in function <...s\LucidNightmareNavigator\libs\NyxGUI-1.0\NyxGUI.lua:198>
[string "@Interface\AddOns\LucidNightmareNavigator\libs\NyxGUI-1.0\NyxGUI.lua"]:208: in function `UpdateWidgetTheme'
[string "@Interface\AddOns\LucidNightmareNavigator\libs\NyxGUI-1.0\NyxGUI.lua"]:312: in function `AddToTheme'
[string "@Interface\AddOns\LucidNightmareNavigator\libs\NyxGUI-1.0\NyxGUI.lua"]:192: in function `New'
[string "@Interface\AddOns\LucidNightmareNavigator\LucidNightmareNavigator.lua"]:880: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5073: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4737: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4773: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: addon = "LucidNightmareNavigator"
w = <unnamed> {
 0 = <userdata>
 backdrop_type = "l0"
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 backdrop_type = "l0"
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
data = <table> {
 LucidNightmareNavigator = <table> {
 }
 NyxGUI = <table> {
 }
}
`

**Comment by Debuggernaut** [comment]
Hey, all right, thanks man.  With that info I was able to figure out the problem.  It should be good to go now

I loaded it up and wandered around the Endless Halls to test it out, and it's working great so far.  Man oh man, I feel like some part of me will always be wandering through that horrible fever dream of a maze

**Comment by DigitallyCreativeDesigns** [comment]
THANK YOU! I appreciate you fixing this so quickly. I woke up to the news, updated the addon and boom MAZE FINALLY DONE! I do hope you are a really bad person though, (although it doesn't seem like it), because only the devil himself should have to wander through that horrible fever dream of a maze forever.

**Comment by keeyla** [comment]
Hi, I downloaded the version that says it was updated three days ago but it's not working at all. :( Not running any other addons at all and it's not just giving me a Lua error. Very frustrating.

**Comment by Debuggernaut** [comment]
Oh, sorry to hear that, could you post the error?  It’s working for me, but
maybe there’s a conflict I can help straighten out

**Comment by keeyla** [comment]
Message: ...dOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua:200: attempt to call method 'GetBackdrop' (a nil value)
Time: Fri Oct 16 20:07:10 2020
Count: 1
Stack: ...dOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua:200: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:200: in function <...dOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua:199>
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:209: in function `UpdateWidgetTheme'
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:313: in function `AddToTheme'
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:193: in function `New'
[string "@Interface\AddOns\LucidNightmareHelper\LucidNightmareHelper.lua"]:542: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5073: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4737: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4773: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: addon = "LucidNightmareHelper"
w = <unnamed> {
 0 = <userdata>
 backdrop_type = "l0"
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 backdrop_type = "l0"
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
data = <table> {
 LucidNightmareHelper = <table> {
 }
 NyxGUI = <table> {
 }
}


This is what it's giving me!

**Comment by Debuggernaut** [comment]
I think that’s the original addon this is forked from, the author probably
hasn’t backported the fix yet

**Comment by keeyla** [comment]
Ohh, should I be just deleting the original Helper addon and only have this one in the Addons folder instead? I know people said this addon was "forked" but I've got no idea what that means for relation to the normal addon so I wasn't sure if I should be stick this Navigator one in the normal Addons folder, or inside the Lucid Nightmare Helper folder or what. @_@ Sorry if these are really obvious questions or things I should be doing!!

**Comment by Debuggernaut** [comment]
Oh, sorry for the confusion

The two addons can coexist, just forget about lnh for now

Download the source code zip of this one, then unzip it and rename the
folder to LucidNightmareNavigator and put that in your WoW addons folder.
The end goal is to have the .toc file in a path like this:  (if I recall
correctly)
retail/interface/addons/LucidNightmareNavigator/LucidNightmareNavigator.toc

Unrelated: Let me apologize in advance that I don’t handle the teleport
trap at the moment, so your map might get to a bad state.. I’d recommend
backing up a copy of it via the “export to box” button every now and then

I’m trying to figure out a way to automatically find and deal with the
trap, but it requires a little too much brainpower, haha.

**Comment by keeyla** [comment]
Okay, thank you so much!! I'll have to let you know in a couple hours when I can play again if it's working but I'll give this a shot!

**Comment by keeyla** [comment]
Alright, it's working for me, thank you so much!! My issue was the folder it was in had "-master" at the end, so just deleted that and it was good to go.

**Comment by Debuggernaut** [comment]
Glad to hear it!

**Comment by justadakaje** [comment]
I had to delete the still-broken LucidNightmareHelper add-on folder for this add-on to work. Thank you SO very much for the work and efforts that went into this. Gotem!

**Comment by Debuggernaut** [comment]
Ohh, I'll bet the broken version of NyxGui in that older addon is
interfering with this one.. I'll tinker with LNN to make sure it uses its
own copy when I get a chance

Thanks for the info!  And congrats on your mount!

**Comment by avrakadeaver** [comment]
hi, so i was just wondering if theres a file missing on the code download for this addon it seems i cannot run it on wow despite having extracted it to the addon folder, the addon screen in wow doesnt seem to acknowledge its there, am i (most likely) missing something or adding it wrong? is there something else i should be looking for? (the other addon seems to no longer be in working order and i was directed to you lol)

**Comment by Debuggernaut** [comment]
Hey buddy, it sounds like it might not be installed correctly

Go to your WoW addons folder, there's some info on how to get there here:
https://www.wowhead.com/addons-how-to-install-and-maintain#installing-installing-the-addon

then make sure you've got a path like this:

World of
Warcraft\_retail_\Interface\Addons\LucidNightmareNavigator\LucidNightmareNavigator.toc

also, be sure to delete LucidNightmareHelper from the Interface\Addons
directory, since there are some conflicts between the two addons right now

Once the addon is installed, you can open it by typing /lnn (that's slash L
N N )

Good luck!

**Comment by avrakadeaver** [comment]
ty soo much,  👍
