### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Columbus337** [Debuggernaut/LucidNightmareHelper#7]
Message: ...dOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua:200: attempt to call method 'GetBackdrop' (a nil value)
Time: Sun Nov 22 19:19:29 2020
Count: 2
Stack: ...dOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua:200: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:200: in function <...dOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua:199>
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:209: in function `UpdateWidgetTheme'
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:313: in function `AddToTheme'
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:193: in function `New'
[string "@Interface\AddOns\LucidNightmareHelper\LucidNightmareHelper.lua"]:542: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5093: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4757: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4793: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: addon = "LucidNightmareHelper"
w = <unnamed> {
 0 = <userdata>
 backdrop_type = "l0"
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 backdrop_type = "l0"
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
data = <table> {
 LucidNightmareHelper = <table> {
 }
 NyxGUI = <table> {
 }
}

**Comment by Debuggernaut** [comment]
Hey buddy, just delete LucidNightmareHelper and you should be good to go

**Comment by Columbus337** [comment]
tried reistalling it bvut the error still comes up when i try to use it

**Comment by Debuggernaut** [comment]
Hey buddy, just delete LucidNightmareHelper and you should be good to go

LucidNightmareHelper is a different addon, and one of its libraries is out of date and conflicts with this addon's newer version
