### ISSUE TITLE
Map doesnt even open anymore

### ISSUE THREAD

**Issue by dirtygirlkush** [Debuggernaut/LucidNightmareHelper#9]
Message: ...dOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua:200: attempt to call method 'GetBackdrop' (a nil value)
Time: Thu Jul 14 09:00:12 2022
Count: 2
Stack: ...dOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua:200: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:200: in function <...dOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua:199>
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:209: in function `UpdateWidgetTheme'
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:313: in function `AddToTheme'
[string "@Interface\AddOns\LucidNightmareHelper\libs\NyxGUI-1.0\NyxGUI.lua"]:193: in function `New'
[string "@Interface\AddOns\LucidNightmareHelper\LucidNightmareHelper.lua"]:542: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5188: in function <Interface\FrameXML\ChatFrame.lua:5134>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4852: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4888: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: addon = "LucidNightmareHelper"
w = <unnamed> {
 0 = <userdata>
 backdrop_type = "l0"
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 backdrop_type = "l0"
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
data = <table> {
 LucidNightmareHelper = <table> {
 }
 NyxGUI = <table> {
 }
}

**Comment by Debuggernaut** [comment]
Check the closed issues on the repo, this is a common occurrence caused by
conflicts with the non-navigating version of the addon.. I should probably
fix it one of these days so this can't happen even if you have that one
installed, but you know how it goes, haha

**Comment by dirtygirlkush** [comment]
I only have one add on for this so what do you mean non navigating version

**Comment by Debuggernaut** [comment]
oh, okay

delete your "LucidNightmareHelper" addon, then download this addon from the
"releases" tab on the side and extract it instead, you should have a path
like this:
_retail_\Addons\LucidNightmareNavigator\LucidNightmareNavigator.toc  (you
can look up more info on how to manually install addons somewhere)

LucidNightmareHelper is the old addon this is based off of that doesn't
have any turn-by-turn navigation built into it

**Comment by Debuggernaut** [comment]
If you can't figure out installing the addon, another option would be to
write down paths from each orb to each receptacle before picking anything
up, then once you've mapped everything out, just follow those paths you
planned out

that'll eliminate almost all of the random wandering and help you get it
done pretty straightforwardly
